language: node_js
node_js:
- '4.1'
before_script:
- node make.js build
before_deploy:
- node make.js after_build
deploy:
  provider: npm
  email: wparad@gmail.com
  api_key:
    secure: fOv0/+B3CNVghkp/+K2smDUGCgttrNgTIKusmyvt/59f3obh6tH1JUae2DYWyII9QuoSI4AgWboO8UPhRxEkMCU3Wp5RwjutVrHCBGpgwgIuX0/Ft7TGyueDfFxj/BrVcvC8o2EXTf33d4DFx9j1QHI3a0Usm4M7vWUNY0CHN2FJIX/Uz0HwCWgZZdR/+AZwkQDDvpmRLeOYoUtVqAI6hIspvyn7Dkai+V6u4vpjKk9DokcvSePCAukrSuoCBd2T7+fI9Bsq3IWHT7hIQWp0CB9uke8WGb073/AEV0Y2Ck53ymfv8q2Yk8a8LFncjUO4xymp+lKdBKOkmhsXSfId89S6puj2JUMPy2EeXjHAe7ymH3x4/E78rTNDbRZ8njgjnyoFwfeLfT+WBg6ykriSpaO9OJMXr7anBPuTFAjhV9aVg4u3MW8odNl2G1Y0tgid6Gq3KzPXyJvuJAhbFNBc3LjVcJSmCOif6tpTmfI1Qv5RShNvFN732fJDjK1BG2zLeZ+H+moZEXmfoGi0I0d8mJR5GUGxAuONVqRP+eLY5rwTnDgYCMqybc5tGl7K1ctfoZ+7YooaOs7S9JGcs0XYuIZyRR3CExLd+dUxW0o3Sg3ozq2WDNF+KoaOLXdWsoyb2QhwCSx7GxQsspqVHEsyJWJ4fW9TjCbwapb1tntGDf0=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
  - secure: AO3GzEOwBDawKij9oDAGVe9EOBIqgv9lIzqyVqDBu2jA4UD2rprAqkJUinm1oukFmBmh5F9N9/DwMelzRyegY5QxTw78u+YL1HgiuE0J8Huv7DOaY/9UyDdRNC47horwYhu7q1awDjs1qUWhTAN81UfYB93NAONpl88eGRNvamZvkfMxlkZoVyqwm2uRVAf21W1+40Lf/fO/xZPSPaEx7/7NncbW+iid5oZX10MdePNyf9wQUr/lqSWYIGyzMAAb7QCy56uvPnTVbShA1P+ugiCoaW24si9XdV549WKPmtuFUSSBiq699Bc42c7o8ztODDfcBMPYP44CCI8hQOSUyabkF4khjxernYOkYWyHw1R67//t/rT9+JT83Knpl3R0Lox+Ph8wwMrTAnTjiCasUYoBumA/MRKCn5G59lQMBL5CcIgI1vXB7UfZ2iMZO6J//pKEhxCca75sC95IPKP6Rckz7tmaPsSvuVkQ0XxLyWsuxayRp+KQj15uaVKDdoUudIIdv1BjIOM71q/Kkf8Nk2iXyjzETVDeL44IOFXKHxx1FHlLHpC2ClQ63STiBmXt670PWA6j43alYOg8InwSVnOAU04uhwpJ2FoMiu1/49asVnyYMhf4/t7NohWh9Eo7sNWQswcYM6ByAMC4zPEt/zU0eQztB0epKSXs6nwlZA8=
